[package]
name = "pow-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1.0"
heck = "0.5.0"
proc-macro-error = "1.0.4"

[dev-dependencies]
assert_tokens_eq = "0.1.0"
